config/routes.rb
SweeperTest::Application.routes.draw do

  resources :users do
    resources :widgets
  end

  root :to => "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :widgets
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  caches_action :show, :layout => false
  cache_sweeper :user_sweeper, :only => [ :create, :update, :delete ]

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  
  expose(:user) { User.find(params[:user_id]) }
  expose(:widgets) { user.widgets }
  expose(:widget)

  cache_sweeper :user_sweeper, :only => [ :create, :update, :delete ]

  # GET /widgets 
  def index   
  end

  # GET /widgets/1  
  def show   
  end

  # GET /widgets/new 
  def new    
  end

  # GET /widgets/1/edit
  def edit    
  end

  # POST /widgets  
  def create   
    if widget.save
      redirect_to([user, widget], :notice => 'Widget was successfully created.')      
    else
      render :action => "new"        
    end    
  end

  # PUT /widgets/1  
  def update   
    if widget.update_attributes(params[:widget])
      redirect_to([user, widget], :notice => 'Widget was successfully updated.')     
    else
      render :action => "edit"     
    end    
  end

  # DELETE /widgets/1  
  def destroy
    widget.destroy
    redirect_to(user_widgets_url(@user))      
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SweeperTest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Widgets', user_widgets_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p><b>Widgets</b></p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.widgets.each do |widget| %>
  <tr>
    <td><%= widget.title %></td>
    <td><%= widget.description %></td>
    <td><%= link_to 'Show', user_widget_path(@user,widget) %></td>
    <td><%= link_to 'Edit', edit_user_widget_path(@user, widget) %></td>
    <td><%= link_to 'Destroy', user_widget_path(@user, widget), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/widgets/_form.html.erb
<%= form_for([user, widget]) do |f| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', [user, widget] %> |
<%= link_to 'Back', user_widgets_path(user) %>

app/views/widgets/index.html.erb
<h1>Listing <%= user.name %> widgets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% widgets.each do |w| %>
  <tr>
    <td><%= w.title %></td>
    <td><%= w.description %></td>
    <td><%= link_to 'Show', user_widget_path(user,w) %></td>
    <td><%= link_to 'Edit', edit_user_widget_path(user, w) %></td>
    <td><%= link_to 'Destroy', user_widget_path(user, w), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Widget', new_user_widget_path(user) %>
<%= link_to 'Back', users_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', user_widgets_path(user) %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= widget.title %>
</p>

<p>
  <b>Description:</b>
  <%= widget.description %>
</p>


<%= link_to 'Edit', edit_user_widget_path(user,widget) %> |
<%= link_to 'Back', user_widgets_path(user) %>